### ISSUE TITLE
Allow test-container resue

### ISSUE THREAD

**Issue by joggeli34** [quarkiverse/quarkus-mockserver#10]
Thanks for the implementation of the extension, this simplifies the usage of the mockserver for us a lot.

It would be great if we could reuse the test-container for multiple test runs. This would speedup the tests by a few seconds.

It could be implemented similar to the database-devservices: https://github.com/quarkusio/quarkus/pull/25367

I would suggest, that it can be enabled/disabled by a property (default false?).

I will create a PR for this feature.

**Comment by andrejpetras** [comment]
Hi @joggeli34, good idea. It would be great if you could prepare PR for it.

**Comment by andrejpetras** [comment]
PR #42

**Comment by andrejpetras** [comment]
Implementation https://github.com/quarkiverse/quarkus-mockserver/pull/42
