### ISSUE TITLE
Doesn't work with native tests

### ISSUE THREAD

**Issue by ghost** [quarkiverse/quarkus-mockserver#145]
In your example, native tests work, because in `application.properties` you set:

    quarkus.rest-client.activity-client.url=${quarkus.mockserver.endpoint}

If you remove that line, `@QuarkusIntegrationTest` fails as native tests are executed with `production` profile by default.

One can enforce usage of `test` profile while executing native test with command line option `-Dquarkus.test.native-image-profile=test`, so e.g. in gradle:

    gradlew testNative -Dquarkus.native.enabled=true -Dquarkus.package.jar.enabled=false -Dquarkus.native.container-build=true -Dquarkus.test.native-image-profile=test -i

One can see that MockServer is started, but it seems the URL is not correctly replaced in `@RestClient`.

**Comment by andrejpetras** [comment]
Hi @porschesstein ,

> This extension provides a `quarkus.mockserver.endpoint` variable that points to the launched Docker container.

there is no `magic` replacement in background, there is only the `quarkus.mockserver.endpoint` property that you can use in your configuration.
If you don't use it, the rest client configuration will use the currently active profile value.
